### ISSUE TITLE
Example of usage to Wiki

### ISSUE THREAD

**Issue by ondrej-duras** [alasdairkeyes/perl-SOAP-WinRM#1]
Hi,
If you will have a while for that,
please give a short example to wiki or to code of project itself.
Many thanks

**Comment by alasdairkeyes** [comment]
Documentation is in Perl POD format within the Perl Module.

`perldoc SOAP::WinRM` will show you the documentation, I don't think it's necessary to duplicate it into the Wiki or the README.md

I've added code block markdown to the README.md to hopefully make the perldoc documentation easier for people to see.
